// Wallet
export const INIT_WALLET = 'INITIALIZE_WALLET';
export const WALLET_CREATE_SUCCESS = 'WALLET_CREATE_SUCCESS';
export const WALLET_CREATE_FAILURE = 'WALLET_CREATE_FAILURE';
export const WALLET_RESTORE_SUCCESS = 'WALLET_RESTORE_SUCCESS';
export const WALLET_RESTORE_FAILURE = 'WALLET_RESTORE_FAILURE';

// App
export const INIT_APP = 'INITIALIZE_APP';
export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';
export const AUTHENTICATION_FAILURE = 'AUTHENTICATION_FAILURE';
export const VERIFICATION_SUCCESS = 'VERIFICATION_SUCCESS';
export const VERIFICATION_FAILURE = 'VERIFICATION_FAILURE';
export const ONBOARDING_COMPLETETED = 'ONBOARDING_COMPLETETED';
export const ONBOARDING_FAILURE = 'ONBOARDING_FAILURE';
