// Wallet
export const INIT_WALLET = 'INIT_WALLET';
export const WALLET_CREATE_SUCCESS = 'WALLET_CREATE_SUCCESS';
export const WALLET_CREATE_FAILURE = 'WALLET_CREATE_FAILURE';
export const WALLET_RESTORE_SUCCESS = 'WALLET_RESTORE_SUCCESS';
export const WALLET_RESTORE_FAILURE = 'WALLET_RESTORE_FAILURE';
export const WALLET_DERIVE_ADDRESS_SUCCESS = 'WALLET_DERIVE_ADDRESS_SUCCESS';
export const WALLET_DERIVE_ADDRESS_FAILURE = 'WALLET_DERIVE_ADDRESS_FAILURE';
export const WALLET_SET_PENDING_TX_SUCCESS = 'WALLET_SET_PENDING_TX_SUCCESS';
export const WALLET_SET_PENDING_TX_FAILURE = 'WALLET_SET_PENDING_TX_FAILURE';
export const WALLET_UNSET_PENDING_TX_SUCCESS = 'WALLET_UNSET_PENDING_TX_SUCCESS';
export const WALLET_UNSET_PENDING_TX_FAILURE = 'WALLET_UNSET_PENDING_TX_FAILURE';
export const WALLET_SET_UTXOS_SUCCESS = 'WALLET_SET_UTXOS_SUCCESS';
export const WALLET_SET_UTXOS_FAILURE = 'WALLET_SET_UTXOS_FAILURE';

// App
export const INIT_APP = 'INIT_APP';
export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';
export const AUTHENTICATION_FAILURE = 'AUTHENTICATION_FAILURE';
export const VERIFICATION_SUCCESS = 'VERIFICATION_SUCCESS';
export const VERIFICATION_FAILURE = 'VERIFICATION_FAILURE';
export const ONBOARDING_COMPLETETED = 'ONBOARDING_COMPLETETED';
export const ONBOARDING_FAILURE = 'ONBOARDING_FAILURE';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
export const CHANGE_NETWORK_SUCCESS = 'CHANGE_NETWORK_SUCCESS';
export const CHANGE_NETWORK_FAILURE = 'CHANGE_NETWORK_FAILURE';

// Onboarding
export const ONBOARDING_SET_PASSWORD = 'ONBOARDING_SET_PASSWORD';
export const ONBOARDING_SET_MNEMONIC = 'ONBOARDING_SET_MNEMONIC';
export const ONBOARDING_SET_VERIFIED = 'ONBOARDING_SET_VERIFIED';
export const ONBOARDING_SET_RESTORED = 'ONBOARDING_SET_RESTORED';
export const ONBOARDING_FLUSH = 'ONBOARDING_FLUSH';

// Transactions history
export const INIT_TXS_HISTORY = 'INIT_TXS_HISTORY';
export const TXS_HISTORY_UPDATE_FAILURE = 'TXS_HISTORY_UPDATE_FAILURE';
export const TXS_HISTORY_SET_TXS_SUCCESS = 'TXS_HISTORY_SET_TXS_SUCCESS';

// Pending transaction
export const PENDING_TX_SET_ASSET = 'PENDING_TX_SET_ASSET';
export const PENDING_TX_SET_ADDRESSES_AND_AMOUNT = 'PENDING_TX_SET_ADDRESSES_AND_AMOUNT';
export const PENDING_TX_SET_FEE_CHANGE_ADDRESS = 'PENDING_TX_SET_FEE_CHANGE_ADDRESS';
export const PENDING_TX_SET_FEE_AMOUNT_AND_ASSET = 'PENDING_TX_SET_FEE_AMOUNT_AND_ASSET';
export const PENDING_TX_FLUSH = 'PENDING_TX_FLUSH';
export const PENDING_TX_SET_TAXI_TOPUP = 'PENDING_TX_SET_TAXI_TOPUP';

// Assets
export const INIT_ASSETS = 'INIT_ASSETS';
export const ASSET_GET_ALL_ASSET_BALANCES_SUCCESS = 'ASSET_GET_BALANCES_SUCCESS';
export const ASSET_GET_ALL_ASSET_BALANCES_FAILURE = 'ASSET_GET_BALANCES_FAILURE';
export const ASSET_UPDATE_ALL_ASSET_INFOS_SUCCESS = 'ASSET_UPDATE_ALL_ASSET_INFOS_SUCCESS';
export const ASSET_UPDATE_ALL_ASSET_INFOS_FAILURE = 'ASSET_UPDATE_ALL_ASSET_INFOS_FAILURE';
