// Wallet
export const WALLET_RESTORE_SUCCESS = 'WALLET_RESTORE_SUCCESS';
export const WALLET_RESTORE_FAILURE = 'WALLET_RESTORE_FAILURE';

// Preferences
export const ONBOARDING_COMPLETETED = 'ONBOARDING_COMPLETETED';
