// Wallet
export const WALLET_SET_DATA = 'WALLET_SET_DATA';
export const ADD_UTXO = 'ADD_UTXO';
export const DELETE_UTXO = 'DELETE_UTXO';
export const FLUSH_UTXOS = 'FLUSH_UTXOS';
export const UPDATE_UTXOS = 'UPDATE_UTXOS';
export const SET_DEEP_RESTORER_GAP_LIMIT = 'SET_DEEP_RESTORER_GAP_LIMIT';
export const SET_DEEP_RESTORER_IS_LOADING = 'SET_DEEP_RESTORER_IS_LOADING';
export const SET_DEEP_RESTORER_ERROR = 'SET_DEEP_RESTORER_ERROR';
export const NEW_ADDRESS_SUCCESS = 'NEW_ADDRESS_SUCCESS';
export const NEW_CHANGE_ADDRESS_SUCCESS = 'NEW_CHANGE_ADDRESS_SUCCESS';

// App
export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';
export const AUTHENTICATION_FAILURE = 'AUTHENTICATION_FAILURE';
export const VERIFICATION_SUCCESS = 'VERIFICATION_SUCCESS';
export const ONBOARDING_COMPLETETED = 'ONBOARDING_COMPLETETED';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const CHANGE_NETWORK_SUCCESS = 'CHANGE_NETWORK_SUCCESS';
export const SET_EXPLORER = 'SET_EXPLORER';

// Onboarding
export const ONBOARDING_SET_MNEMONIC_AND_PASSWORD = 'ONBOARDING_SET_MNEMONIC_AND_PASSWORD';
export const ONBOARDING_SET_VERIFIED = 'ONBOARDING_SET_VERIFIED';
export const ONBOARDING_SET_RESTORED = 'ONBOARDING_SET_RESTORED';
export const ONBOARDING_FLUSH = 'ONBOARDING_FLUSH';
export const ONBOARDING_SET_IS_FROM_POPUP_FLOW = 'ONBOARDING_SET_IS_FROM_POPUP_FLOW';

// Transactions history
export const UPDATE_TXS = 'UPDATE_TXS';
export const ADD_TX = 'ADD_TX';

// Pending transaction
export const PENDING_TX_SET_ASSET = 'PENDING_TX_SET_ASSET';
export const PENDING_TX_SET_ADDRESSES_AND_AMOUNT = 'PENDING_TX_SET_ADDRESSES_AND_AMOUNT';
export const PENDING_TX_SET_FEE_CHANGE_ADDRESS = 'PENDING_TX_SET_FEE_CHANGE_ADDRESS';
export const PENDING_TX_SET_FEE_AMOUNT_AND_ASSET = 'PENDING_TX_SET_FEE_AMOUNT_AND_ASSET';
export const PENDING_TX_FLUSH = 'PENDING_TX_FLUSH';
export const PENDING_TX_SET_PSET = 'PENDING_TX_SET_PSET';

// Assets
export const ADD_ASSET = 'ADD_ASSET';

// Connect data
export const ENABLE_WEBSITE = 'ENABLE_WEBSITE';
export const DISABLE_WEBSITE = 'DISABLE_WEBSITE';
export const SET_TX = 'SET_TX';
export const FLUSH_TX = 'FLUSH_TX';
export const SET_MSG = 'SET_MSG';
export const FLUSH_MSG = 'FLUSH_MSG';
export const SELECT_HOSTNAME = 'SELECT_HOSTNAME';
export const FLUSH_SELECTED_HOSTNAME = 'FLUSH_SELECTED_HOSTNAME';

// Taxi
export const SET_TAXI_ASSETS = 'SET_TAXI_ASSETS';
export const UPDATE_TAXI_ASSETS = 'UPDATE_TAXI_ASSETS';

// Alarms
export const START_PERIODIC_UPDATE = 'START_PERIODIC_UPDATE';

// Restoration
export const START_DEEP_RESTORATION = 'START_DEEP_RESTORATION';
