// Wallet
export const WALLET_CREATE_SUCCESS = 'WALLET_CREATE_SUCCESS';
export const WALLET_CREATE_FAILURE = 'WALLET_CREATE_FAILURE';
export const WALLET_RESTORE_SUCCESS = 'WALLET_RESTORE_SUCCESS';
export const WALLET_RESTORE_FAILURE = 'WALLET_RESTORE_FAILURE';
export const WALLET_SET_ADDRESS_SUCCESS = 'WALLET_SET_ADDRESS_SUCCESS';
export const WALLET_SET_ADDRESS_FAILURE = 'WALLET_SET_ADDRESS_FAILURE';
export const ADD_UTXO = 'ADD_UTXO';
export const DELETE_UTXO = 'DELETE_UTXO';
export const UPDATE_UTXOS = 'UPDATE_UTXOS';

// App
export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';
export const AUTHENTICATION_FAILURE = 'AUTHENTICATION_FAILURE';
export const VERIFICATION_SUCCESS = 'VERIFICATION_SUCCESS';
export const VERIFICATION_FAILURE = 'VERIFICATION_FAILURE';
export const ONBOARDING_COMPLETETED = 'ONBOARDING_COMPLETETED';
export const ONBOARDING_FAILURE = 'ONBOARDING_FAILURE';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
export const CHANGE_NETWORK_SUCCESS = 'CHANGE_NETWORK_SUCCESS';
export const CHANGE_NETWORK_FAILURE = 'CHANGE_NETWORK_FAILURE';

// Onboarding
export const ONBOARDING_SET_MNEMONIC_AND_PASSWORD = 'ONBOARDING_SET_MNEMONIC_AND_PASSWORD';
export const ONBOARDING_SET_VERIFIED = 'ONBOARDING_SET_VERIFIED';
export const ONBOARDING_SET_RESTORED = 'ONBOARDING_SET_RESTORED';
export const ONBOARDING_FLUSH = 'ONBOARDING_FLUSH';

// Transactions history
export const INIT_TXS_HISTORY = 'INIT_TXS_HISTORY';
export const TXS_HISTORY_SET_TXS_SUCCESS = 'TXS_HISTORY_SET_TXS_SUCCESS';
export const UPDATE_TXS = 'UPDATE_TXS';

// Pending transaction
export const PENDING_TX_SET_ASSET = 'PENDING_TX_SET_ASSET';
export const PENDING_TX_SET_ADDRESSES_AND_AMOUNT = 'PENDING_TX_SET_ADDRESSES_AND_AMOUNT';
export const PENDING_TX_SET_FEE_CHANGE_ADDRESS = 'PENDING_TX_SET_FEE_CHANGE_ADDRESS';
export const PENDING_TX_SET_FEE_AMOUNT_AND_ASSET = 'PENDING_TX_SET_FEE_AMOUNT_AND_ASSET';
export const PENDING_TX_FLUSH = 'PENDING_TX_FLUSH';
export const PENDING_TX_SET_PSET = 'PENDING_TX_SET_PSET';

// Assets
export const ASSET_GET_ALL_ASSET_BALANCES_SUCCESS = 'ASSET_GET_BALANCES_SUCCESS';
export const ASSET_GET_ALL_ASSET_BALANCES_FAILURE = 'ASSET_GET_BALANCES_FAILURE';
export const ASSET_UPDATE_ALL_ASSET_INFOS_SUCCESS = 'ASSET_UPDATE_ALL_ASSET_INFOS_SUCCESS';
export const UPDATE_ASSETS = 'UPDATE_ASSETS';

// Connect data
export const ENABLE_WEBSITE = 'ENABLE_WEBSITE';
export const DISABLE_WEBSITE = 'DISABLE_WEBSITE';
export const SET_TX = 'SET_TX';
export const FLUSH_TX = 'FLUSH_TX';
export const SET_MSG = 'SET_MSG';
export const FLUSH_MSG = 'FLUSH_MSG';
export const SELECT_HOSTNAME = 'SELECT_HOSTNAME';
export const FLUSH_SELECTED_HOSTNAME = 'FLUSH_SELECTED_HOSTNAME';

// Taxi
export const SET_TAXI_ASSETS = 'SET_TAXI_ASSETS';
export const UPDATE_TAXI_ASSETS = 'UPDATE_TAXI_ASSETS';
